function  phi = phix3y(x,y,hlen);
%  third-order cross-correlation function
%
%  Syntax:  phi = phix3y(x,y,hlen);

%  Computes the third-order cross-correlation between x and y out to
%  hlen-1 lags. Implemented as a MEX file, for obvious reasons.
%
%  DTW June 1994   pointer to MEX file only

disp('This function is implemented as a MEX file.');
disp('If MATLAB is giving you this message, the nlid toolbox MEX files');
disp('have not been installed for your machine architecture');
